#CodeAssist project settings
#Sun Oct 04 11:31:18 GMT+05:00 2026
tree.expanded.Project=root\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/llmapi/app/src/main/kotlin\nroot\:/storage/emulated/0/Android/data/com.tyron.code/files/codeassist/projects/llmapi/app/src/main/res\nmodule\:app\nworkspace
